### ISSUE TITLE
Can't read language spec

### ISSUE THREAD

**Issue by zanderdk** [pietroborrello/ghidra-atom-microcode#1]
When i follow the install instruction I get a Ghidra popup "can't read language spec" with the folloing path
/opt/ghidra/Ghidra/Processors/ghidra-atom-microcode/data/languages/x86ucde.sla

Could this file potentialy be missing from the project or am i just being stupid and can't follow simple instalation instruction??
Help much appreciated. :-)

**Comment by zanderdk** [comment]
I Also tried using gradle to build it but also with no success as the data dir is simply just copied and will stil lack the x86ucde.sla file.

**Comment by zanderdk** [comment]
it seams like this commit removed a esentila file 4be2235704d2ee5e667e4963642aad00b7eb272f.

**Comment by pietroborrello** [comment]
So, "in theory", I removed the files since Ghidra will automatically build the `sla` file the first time you load the microcode file. This is better since it will be tied to your Ghidra version and not my Ghidra version, which could result in some incompatibilities. 

Which ghidra version do you have? And also, have you cloned the repo in `<ghidra install dir>/Ghidra/Processors/`, checking that it is the installation directory of the specific ghidra version you are executing?

Also, can you paste the output of:
```
./Features/Decompiler/os/linux64/sleigh Processors/ghidra-atom-microcode/data/languages/x86ucode.slaspec 
```
Executed in the `<ghidra install dir>/Ghidra` folder? (I assume you are running on linux, use `./Features/Decompiler/os/osx64/sleigh` or `./Features/Decompiler/os/win64/sleigh` otherwise)

I can push the sla file, but I would like to avoid that since it is a bit risky in case some ghidra version has breaking changes.

**Comment by zanderdk** [comment]
Im using version 10.1.5_DEV and yes i have cloned directly in /opt/ghidra == my `<ghidra install dir>`. Which version are you using?

ouput of sleigh:
```bash
10026 zander:Ghidra/ $ ./Features/Decompiler/os/linux_x86_64/sleigh Processors/ghidra-atom-microcode/data/languages/x86ucode.slaspec
WARN  8 NOP constructors found
WARN  Use -n switch to list each individually
WARN  3 unnecessary extensions/truncations were converted to copies
WARN  Use -u switch to list each individually
WARN  x86ucode.slaspec:522: Unreferenced table 'source0_target_imm'
WARN  x86ucode.slaspec:543: Unreferenced table 'source1_noalias'
WARN  x86ucode.slaspec:1943: Unreferenced table 'ldstad_mode'
10027 zander:Ghidra/ $ pwd
/opt/ghidra/Ghidra
10028 zander:Ghidra/ $
``` 
I have no `./Features/Decompiler/os/linux64/sleigh` but assuming `./Features/Decompiler/os/linux_x86_64/sleigh` is same shit.

**Comment by zanderdk** [comment]
here you also have giant ghidra stacktrace:

```
Invalid processor specification file: /opt/ghidra/Ghidra/Processors/ghidra-atom-microcode/data/languages/x86ucode.pspec
ghidra.app.plugin.processors.sleigh.SleighException: Invalid processor specification file: /opt/ghidra/Ghidra/Processors/ghidra-atom-microcode/data/languages/x86ucode.pspec
	at ghidra.app.plugin.processors.sleigh.SleighLanguageValidator.validateSleighFile(SleighLanguageValidator.java:222)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageValidator.validatePspecFile(SleighLanguageValidator.java:191)
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.initialize(SleighLanguage.java:134)
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.<init>(SleighLanguage.java:111)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.getNewSleigh(SleighLanguageProvider.java:112)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.getLanguage(SleighLanguageProvider.java:99)
	at ghidra.program.util.DefaultLanguageService$LanguageInfo.lambda$getLanguage$0(DefaultLanguageService.java:385)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.sun.msv.verifier.ValidityViolation; lineNumber: 8; columnNumber: 109; at least one of the following attributes is required for element "memory_block": bit_mapped_address,byte_mapped_address,initialized
	at com.sun.msv.verifier.Verifier.onError(Verifier.java:367)
	at com.sun.msv.verifier.Verifier.onError(Verifier.java:363)
	at com.sun.msv.verifier.Verifier.startElement(Verifier.java:232)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2726)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at org.iso_relax.verifier.impl.VerifierImpl.verify(VerifierImpl.java:121)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageValidator.validateSleighFile(SleighLanguageValidator.java:217)
	... 12 more

---------------------------------------------------
Build Date: 2022-Aug-14 1349 UTC
Ghidra Version: 10.1.5
Java Home: /usr/lib/jvm/java-18-openjdk
JVM Version: N/A 18.0.2
OS: Linux 5.19.7-arch1-1 amd64
```

**Comment by pietroborrello** [comment]
Ah interesting, so the error is in the pspec file and not the slaspec file. It seems now `initialized` is required for memory regions in newer ghidra, I'll fix it soon (tomorrow-ish).
I'm using 10.0, but I'll update

**Comment by zanderdk** [comment]
Thanks a lot, looking forward.

**Comment by pietroborrello** [comment]
Commit a90f2211983749ff60af66208ffaebb2a43fd021 should fix the issue
